// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Controls.dashboard__dash = (function(_super) {
    __extends(dashboard__dash, _super);

    function dashboard__dash() {
      return dashboard__dash.__super__.constructor.apply(this, arguments);
    }

    dashboard__dash.prototype.createDom = function() {
      return "<div class=\"control container dashboard-dash\">\n    <div class=\"container widget-container container-0\" data-index=\"0\">\n    </div>\n    <div class=\"container widget-container container-1\" data-index=\"1\">\n    </div>\n    <div class=\"widget-storage\"><children></div>\n    <div class=\"container trash\">\n        <i class=\"icon-trash\"></i>\n    </div>\n</div>";
    };

    dashboard__dash.prototype.setupDom = function(dom) {
      dashboard__dash.__super__.setupDom.call(this, dom);
      jQuery(this.dom).children('.container').sortable({
        connectWith: '.dashboard-dash .container',
        handle: '.handle',
        revert: 200,
        placeholder: 'placeholder',
        tolerance: 'pointer',
        start: (function(_this) {
          return function() {
            return _this.event('drag_start', {});
          };
        })(this),
        stop: (function(_this) {
          return function() {
            var r;
            _this.event('drag_stop', {});
            r = {};
            $(_this.dom).children('.widget-container').each(function(i, c) {
              var index;
              index = parseInt($(c).attr('data-index'));
              r[index] = [];
              return $(c).children().each(function(i, e) {
                return r[index].push(parseInt($(e).attr('data-uid')));
              });
            });
            return _this.event('reorder', {
              indexes: r
            });
          };
        })(this)
      });
      return $(this.dom).find('.widget-storage > *').each((function(_this) {
        return function(i, e) {
          return $(_this.dom).find(".container-" + ($(e).attr('data-container'))).append(e);
        };
      })(this));
    };

    return dashboard__dash;

  })(window.Control);

  window.Controls.dashboard__widget = (function(_super) {
    __extends(dashboard__widget, _super);

    function dashboard__widget() {
      return dashboard__widget.__super__.constructor.apply(this, arguments);
    }

    dashboard__widget.prototype.createDom = function() {
      return "<div data-uid=\"" + this.properties.uid + "\" data-container=\"" + this.properties.container + "\" class=\"control dashboard-widget\">\n    <div class=\"handle\"></div>\n    <div class=\"content __child-container\"><children></div>\n    <a class=\"configure\"><i class=\"icon-wrench\"></i></a>\n    <a class=\"delete\"><i class=\"icon-remove\"></i></a>\n</div>";
    };

    dashboard__widget.prototype.setupDom = function(dom) {
      dashboard__widget.__super__.setupDom.call(this, dom);
      if (!this.properties.configurable) {
        $(this.dom).children('a.configure').remove();
      }
      $(this.dom).children('a.configure').click((function(_this) {
        return function() {
          return _this.event('configure', {});
        };
      })(this));
      return $(this.dom).children('a.delete').click((function(_this) {
        return function() {
          return _this.event('delete', {});
        };
      })(this));
    };

    return dashboard__widget;

  })(window.Control);

  window.Controls.dashboard__header = (function(_super) {
    __extends(dashboard__header, _super);

    function dashboard__header() {
      return dashboard__header.__super__.constructor.apply(this, arguments);
    }

    dashboard__header.prototype.createDom = function() {
      return "<div class=\"control dashboard-header\">\n      <div class=\"labels\" style=\"padding-left:20px\">\n        <div class=\"hostname\">" + (this.s(this.properties.hostname)) + "</div>\n        <div class=\"distro\">DIG Engineering Kiosk 0.1</div>\n    </div>\n\n    <div class=\"inner\"><children></div>\n</div>";
    };

    return dashboard__header;

  })(window.Control);

  window.Controls.dashboard__welcome = (function(_super) {
    __extends(dashboard__welcome, _super);

    function dashboard__welcome() {
      return dashboard__welcome.__super__.constructor.apply(this, arguments);
    }

    dashboard__welcome.prototype.createDom = function() {
      return "<div class=\"control container welcome\">\n    Welcome to Ajenti.<br/>\n    Use the <b>Feedback</b> link to send us your suggestions!<br/>\n\n    <br/>\n    Follow @ajenti for news and announcements.</br>\n    \n    <iframe allowtransparency=\"true\" frameborder=\"0\" scrolling=\"no\" src=\"//platform.twitter.com/widgets/follow_button.html?screen_name=ajenti&show_count=true&dnt=true\" style=\"width:300px; height:20px;\"></iframe>\n    <br/>\n    <br/>\n\n    <a href=\"mailto:e@ajenti.org\">Send e-mail</a> if you have private/security questions or issues.<br/>\n    <br/>\n    <b>Don't forget to change default password in the Configurator!</b>\n</div>";
    };

    return dashboard__welcome;

  })(window.Control);

}).call(this);
